In [5]:
import pandas as pd

In [7]:
df=pd.read_csv("abalone.csv")

In [9]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [11]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [13]:
df.tail()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12

In [15]:
df.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [17]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [19]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [23]:
df["Sex"].value_counts()

Sex
M    1528
I    1342
F    1307
Name: count, dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["Sex"]=label_encoder.fit_transform(df["Sex"])

In [31]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [33]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [35]:
x=df.drop("Rings",axis=1)
y=df["Rings"]

In [37]:
x

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  
0             0.1010        0.1500  
1             0.0485        0.0700  
2             0.1415        0.2100  
3             0.1140        0.1550  
4             0.0395        0.0550  
...              ...           ...  
4172          0.2390        0.2490  
4173          0.2145        0.2605  
4174          0.2875        0.3080  
4175          0.2610        0.2960  
4176          0.3765        0.4950  

[4177 rows x 8 columns]

In [39]:
y

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
len(x_train),len(y_train)

(3341, 3341)

In [45]:
len(x_test),len(y_test)

(836, 836)

In [47]:
x_train

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4038    1   0.550     0.445   0.125        0.6720          0.2880   
1272    1   0.475     0.355   0.100        0.5035          0.2535   
3384    0   0.305     0.225   0.070        0.1485          0.0585   
3160    1   0.275     0.200   0.065        0.1165          0.0565   
3894    2   0.495     0.380   0.135        0.6295          0.2630   
...   ...     ...       ...     ...           ...             ...   
3444    0   0.490     0.400   0.115        0.5690          0.2560   
466     0   0.670     0.550   0.190        1.3905          0.5425   
3092    2   0.510     0.395   0.125        0.5805          0.2440   
3772    2   0.575     0.465   0.120        1.0535          0.5160   
860     0   0.595     0.475   0.160        1.1405          0.5470   

      Viscera weight  Shell weight  
4038          0.1365         0.210  
1272          0.0910         0.140  
3384          0.0335         0.045  
3160          0.0130         0.035  
3894          0.1425         0.215  
...              ...           ...  
3444          0.1325         0.145  
466           0.3035         0.400  
3092          0.1335         0.188  
3772          0.2185         0.235  
860           0.2310         0.271  

[3341 rows x 8 columns]

In [49]:
y_train

4038    11
1272     8
3384     7
3160     7
3894    12
        ..
3444     9
466     12
3092    11
3772     9
860      6
Name: Rings, Length: 3341, dtype: int64

In [51]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [53]:
lr.fit(x_train,y_train)

LinearRegression()

In [57]:
lr.score(x_test,y_test)

0.5323381317508206

In [59]:
x_test

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
866     2   0.605     0.455   0.160        1.1035          0.4210   
1483    2   0.590     0.440   0.150        0.8725          0.3870   
599     0   0.560     0.445   0.195        0.9810          0.3050   
1702    0   0.635     0.490   0.170        1.2615          0.5385   
670     2   0.475     0.385   0.145        0.6175          0.2350   
...   ...     ...       ...     ...           ...             ...   
3093    0   0.520     0.430   0.150        0.7280          0.3020   
1651    0   0.595     0.435   0.150        0.9000          0.4175   
2897    1   0.545     0.430   0.150        0.7420          0.3525   
3953    1   0.465     0.355   0.120        0.5805          0.2550   
1830    1   0.365     0.275   0.085        0.2230          0.0980   

      Viscera weight  Shell weight  
866           0.3015         0.325  
1483          0.2150         0.245  
599           0.2245         0.335  
1702          0.2665         0.380  
670           0.1080         0.215  
...              ...           ...  
3093          0.1575         0.235  
1651          0.1700         0.265  
2897          0.1580         0.208  
3953          0.0915         0.184  
1830          0.0375         0.075  

[836 rows x 8 columns]

In [61]:
x_test.iloc[0]

Sex               2.0000
Length            0.6050
Diameter          0.4550
Height            0.1600
Whole weight      1.1035
Shucked weight    0.4210
Viscera weight    0.3015
Shell weight      0.3250
Name: 866, dtype: float64

In [63]:
demo_input = x_test.iloc[0].to_numpy()

In [65]:
demo_input

array([2.    , 0.605 , 0.455 , 0.16  , 1.1035, 0.421 , 0.3015, 0.325 ])

In [67]:
lr.predict([demo_input])

C:\Users\DELL\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.69320349])

In [69]:
y_test.iloc[0]

np.int64(9)

In [71]:
lr.coef_

array([  0.08418964,  -1.53945918,  13.59793755,  11.44839996,
         9.15739582, -20.68102468,  -8.75282231,   8.64847518])

In [73]:
lr.intercept_

np.float64(2.867138039095429)

In [75]:
lr.feature_names_in_

array(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight',
       'Shucked weight', 'Viscera weight', 'Shell weight'], dtype=object)

In [77]:
lr.n_features_in_

8

In [85]:
Sex=x_test.iloc[0]["Sex"]
Length=x_test.iloc[0]["Length"]
Diameter=x_test.iloc[0]["Diameter"]
Height	=x_test.iloc[0]["Height"]
Whole_weight=x_test.iloc[0]["Whole weight"]
Shucked_weight=x_test.iloc[0]["Shucked weight"]
Viscera_weight=x_test.iloc[0]["Viscera weight"]
Shell_weight=x_test.iloc[0]["Shell weight"]

In [95]:
predicted_age=(
lr.coef_[0] *Sex +lr.coef_[1] *Length + lr.coef_[2] * Diameter + lr.coef_[3] * Height +lr.coef_[4] * Whole_weight +lr.coef_[5] * Shucked_weight +lr.coef_[6] * Viscera_weight + lr.coef_[7] * Shell_weight +lr.intercept_)

In [97]:
predicted_age

np.float64(11.693203491960539)